### ISSUE TITLE
how explain this error

### ISSUE THREAD

**Issue by hkbk** [frideosapps/data_examples#1]
Error: Method not found: 'StreamedValue'.
  final dateTime = StreamedValue<String>();

**Comment by frideosapps** [comment]
Hello @hkbk, I've just updated the example to the last version of the package. Since the v0.6.0 of the frideos package you need to add this import in order to use all the classes that implement the `StreamedObject` interface:

` import 'package:frideos_core/frideos_core.dart'`

Check out these docs for detailed info: [frideos](https://pub.dartlang.org/packages/frideos#-readme-tab-) and [frideos_core](https://pub.dartlang.org/packages/frideos_core#-readme-tab-).
